------------------------------계정(ACCOUNT) 테이블--------------------------

CREATE TABLE ACCOUNT(
    A_ID        NUMBER,
    A_UID       VARCHAR2(30 CHAR),      -- 아이디
    A_PW        VARCHAR2(30 CHAR),      -- 비밀번호
    A_NAME      VARCHAR2(30 CHAR),      -- 이름
    A_BDATE     VARCHAR2(30 CHAR),      -- 생년월일
    A_JDATE     DATE,                   -- 가입일
    A_EMAIL     VARCHAR2(50 CHAR),      -- 이메일
    A_AD        VARCHAR2(100 CHAR),     -- 주소
    A_PHONE     VARCHAR2(30 CHAR),      -- 핸드폰번호
    A_PHOTO     VARCHAR2(500 CHAR),      -- 프로필 사진 이름
    A_GENDER    CHAR(1),                -- 성별
    A_KAKAO     VARCHAR2(30 CHAR),      -- 카카오 아이디
    A_GOOGLE    VARCHAR2(30 CHAR)       -- 구글 아이디
);

CREATE SEQUENCE A_ID NOCACHE;

ALTER TABLE ACCOUNT ADD CONSTRAINT A_ID_PK PRIMARY KEY(A_ID);
ALTER TABLE ACCOUNT MODIFY A_UID CONSTRAINT A_UID_NN NOT NULL;
ALTER TABLE ACCOUNT MODIFY A_PW CONSTRAINT A_PW_NN NOT NULL;
ALTER TABLE ACCOUNT MODIFY A_NAME CONSTRAINT A_NAME_NN NOT NULL;
ALTER TABLE ACCOUNT MODIFY A_BDATE CONSTRAINT A_BDATE_NN NOT NULL;
ALTER TABLE ACCOUNT MODIFY A_JDATE DATE DEFAULT(SYSDATE);
ALTER TABLE ACCOUNT MODIFY A_EMAIL CONSTRAINT A_EMAIL_NN NOT NULL;
ALTER TABLE ACCOUNT MODIFY A_AD CONSTRAINT A_AD_NN NOT NULL;
ALTER TABLE ACCOUNT MODIFY A_PHONE CONSTRAINT A_PHONE_NN NOT NULL;
ALTER TABLE ACCOUNT ADD CONSTRAINT A_GENDER_CK CHECK(A_GENDER IN ('M','W'));

----------------------------관리자(ADMIN) 테이블--------------------------

CREATE TABLE AD(
    AD_ID       NUMBER,                 
    A_ID        NUMBER                  -- 유저아이디
);

CREATE SEQUENCE AD_ID NOCACHE;

ALTER TABLE AD ADD CONSTRAINT AD_ID_PK PRIMARY KEY(AD_ID);
ALTER TABLE AD ADD CONSTRAINT AD_A_ID_FK FOREIGN KEY(A_ID) REFERENCES ACCOUNT(A_ID) ON DELETE CASCADE;

----------------------------모임 카테고리(CG) 테이블--------------------------

CREATE TABLE CG(
    CG_ID       NUMBER,                
    CG_NAME     VARCHAR2(10 CHAR)       -- 카테고리 이름
);

CREATE SEQUENCE CG_ID NOCACHE;

ALTER TABLE CG ADD CONSTRAINT CG_ID_PK PRIMARY KEY(CG_ID);
ALTER TABLE CG MODIFY CG_NAME CONSTRAINT CG_NAME_NN NOT NULL;

--------------------------------모임(CLUB) 테이블-------------------------------

CREATE TABLE CLUB(
    C_ID        NUMBER,                 
    C_NAME      VARCHAR2(30 CHAR),      -- 모임 이름
    C_SDATE     DATE,                   -- 모임 생성일
    C_PHOTO     VARCHAR2(500 CHAR),      -- 모임 프로필 사진 이름
    C_OPEN      CHAR,                   -- 모임 공개여부
    CG_ID       NUMBER,                 -- 모임 카테고리 번호
    C_CHAT      NUMBER               -- 모임 채팅방 번호
);

CREATE SEQUENCE C_ID NOCACHE;
CREATE SEQUENCE C_CHAT NOCACHE;

ALTER TABLE CLUB ADD CONSTRAINT C_ID_PK PRIMARY KEY(C_ID);
ALTER TABLE CLUB MODIFY C_NAME CONSTRAINT C_NAME_NN NOT NULL;
ALTER TABLE CLUB MODIFY C_SDATE DEFAULT(SYSDATE);
ALTER TABLE CLUB MODIFY C_OPEN CONSTRAINT C_OPEN_NN NOT NULL;
ALTER TABLE CLUB ADD CONSTRAINT CLUB_CG_ID_FK FOREIGN KEY(CG_ID) REFERENCES CG(CG_ID);
ALTER TABLE CLUB ADD C_DISCRIPTION VARCHAR2(1000 CHAR);


--------------------------------모임 가입(APPLY) 테이블-------------------------------

CREATE TABLE AP(
    AP_ID       NUMBER,
    AP_STATE    CHAR(1),                 -- 모임 가입 상태
    C_ID        NUMBER,                  -- 모임 번호
    A_ID        NUMBER                   -- 유저 번호
);

CREATE SEQUENCE AP_ID NOCACHE;

ALTER TABLE AP ADD CONSTRAINT AP_ID_PK PRIMARY KEY(AP_ID);
AlTER TABLE
ALTER TABLE AP ADD CONSTRAINT AP_STATE_CK CHECK(AP_STATE IN ('Y','N'));
ALTER TABLE AP ADD CONSTRAINT AP_C_ID_FK FOREIGN KEY(C_ID) REFERENCES CLUB(C_ID) ON DELETE CASCADE;
ALTER TABLE AP ADD CONSTRAINT AP_A_ID_FK FOREIGN KEY(A_ID) REFERENCES ACCOUNT(A_ID) ON DELETE CASCADE;

--------------------------------회원(MEMBER) 테이블-------------------------------

CREATE TABLE MEMBER(
    M_ID        NUMBER,
    P_CHIEF     CHAR(1),        -- 모임장 권한
    P_CNTL      CHAR(1),        -- 멤버관리 권한
    P_WRITE     CHAR(1),        -- 글쓰기 권한
    P_JOIN      CHAR(1),        -- 모임참여 권한
    J_NUM       NUMBER,         -- 모임참여 횟수
    A_ID        NUMBER,         -- 유저 번호
    C_ID        NUMBER          -- 모임 번호
);

CREATE SEQUENCE M_ID NOCACHE;

ALTER TABLE MEMBER ADD CONSTRAINT M_ID_PK PRIMARY KEY(M_ID);
ALTER TABLE MEMBER ADD CONSTRAINT P_CHIEF_CK CHECK(P_CHIEF IN ('Y','N'));
ALTER TABLE MEMBER ADD CONSTRAINT P_CNTL_CK CHECK(P_CNTL IN ('Y','N'));
ALTER TABLE MEMBER ADD CONSTRAINT P_WRITE_CK CHECK(P_WRITE IN ('Y','N'));
ALTER TABLE MEMBER ADD CONSTRAINT P_JOIN_CK CHECK(P_JOIN IN ('Y','N'));
ALTER TABLE MEMBER MODIFY J_NUM NUMBER DEFAULT(0);
ALTER TABLE MEMBER ADD CONSTRAINT M_A_ID_FK FOREIGN KEY(A_ID) REFERENCES ACCOUNT(A_ID) ON DELETE CASCADE;
ALTER TABLE MEMBER ADD CONSTRAINT M_C_ID_FK FOREIGN KEY(C_ID) REFERENCES CLUB(C_ID) ON DELETE CASCADE;


--------------------------------모임(MEETING) 테이블-------------------------------

CREATE TABLE MT(
    MT_ID       NUMBER,
    MT_NAME     VARCHAR2(30 CHAR),          -- 모임 이름
    MT_DS       VARCHAR2(200 CHAR),          -- 모임 설명
    MT_AD       VARCHAR2(200 CHAR),          -- 모임 장소
    MT_PRICE    NUMBER,                     -- 참가비
    MT_SDATE    DATE,                       -- 모임 시작 날짜
    MT_FDATE    DATE,                       -- 모임 종료 날짜
    MT_PHOTO    VARCHAR2(200 CHAR),          -- 모임 프로필 사진 이름
    MT_P        NUMBER                      -- 모임 인원 수
    C_ID        NUMBER                      -- 모임 번호
);

CREATE SEQUENCE MT_ID NOCACHE;

ALTER TABLE MT ADD CONSTRAINT MT_ID_PK PRIMARY KEY(MT_ID);
ALTER TABLE MT MODIFY MT_NAME CONSTRAINT MT_NAME_NN NOT NULL;
ALTER TABLE MT MODIFY MT_AD CONSTRAINT MT_AD_NN NOT NULL;
ALTER TABLE MT MODIFY MT_PRICE NUMBER DEFAULT(0);
ALTER TABLE MT MODIFY MT_SDATE CONSTRAINT MT_SDATE_NN NOT NULL;
ALTER TABLE MT MODIFY MT_FDATE CONSTRAINT MT_FDATE_NN NOT NULL;
ALTER TABLE MT MODIFY MT_P NUMBER DEFAULT(100);
ALTER TABLE MT ADD CONSTRAINT MT_C_ID_FK FOREIGN KEY(C_ID) REFERENCES CLUB(C_ID) ON DELETE CASCADE;


--------------------------------모임 인원(MEETING MEMBER) 테이블-------------------------------

CREATE TABLE MM(
    MM_ID       NUMBER,
    M_ID        NUMBER,     -- 회원 번호
    MT_ID       NUMBER,     -- 일정 번호
    MM_MASTER   CHAR        -- 일정장
);

CREATE SEQUENCE MM_ID NOCACHE;

ALTER TABLE MM ADD CONSTRAINT MM_ID_PK  PRIMARY KEY(MM_ID);
ALTER TABLE MM ADD CONSTRAINT MM_M_ID_FK FOREIGN KEY(M_ID) REFERENCES MEMBER(M_ID) ON DELETE CASCADE;
ALTER TABLE MM ADD CONSTRAINT MM_MT_ID_FK FOREIGN KEY(MT_ID) REFERENCES MT(MT_ID) ON DELETE CASCADE;
ALTER TABLE MM ADD CONSTRAINT MM_MASTER_CK CHECK(MM_MASTER IN ('Y','N'));

--------------------------------게시판(BOARD) 테이블-------------------------------

CREATE TABLE BOARD(
    B_ID        NUMBER,
    B_NAME      VARCHAR2(30 CHAR),      -- 게시글 제목
    B_CONTENT   VARCHAR2(1000 CHAR),    -- 게시글 내용
    B_PHOTO     CHAR,                   -- 게시글 사진 포함 여부
    B_DATE      DATE,                   -- 게시글 작성일
    B_GOOD      NUMBER,                 -- 게시글 좋아요 수
    B_PEOPLE    NUMBER,                 -- 게시글 방문자 수
    C_ID        NUMBER,                 -- 모임 번호
    M_ID        NUMBER                  -- 회원 번호
);

CREATE SEQUENCE B_ID NOCACHE;

ALTER TABLE BOARD ADD CONSTRAINT B_ID_PK PRIMARY KEY(B_ID);
ALTER TABLE BOARD MODIFY B_NAME CONSTRAINT B_NAME_NN NOT NULL;
ALTER TABLE BOARD MODIFY B_CONTENT CONSTRAINT B_CONTENT_NN NOT NULL;
ALTER TABLE BOARD ADD CONSTRAINT B_PHOTO_CK CHECK(B_PHOTO IN ('Y','N'));
ALTER TABLE BOARD MODIFY B_DATE DATE DEFAULT(SYSDATE);
ALTER TABLE BOARD MODIFY B_GOOD NUMBER DEFAULT(0);
ALTER TABLE BOARD MODIFY B_PEOPLE NUMBER DEFAULT(0);
ALTER TABLE BOARD ADD CONSTRAINT B_C_ID_FK FOREIGN KEY(C_ID) REFERENCES CLUB(C_ID) ON DELETE CASCADE;
ALTER TABLE BOARD ADD CONSTRAINT B_M_ID_FK FOREIGN KEY(M_ID) REFERENCES MEMBER(M_ID) ON DELETE CASCADE;

--------------------------------게시글 사진(PHOTO) 테이블-------------------------------

CREATE TABLE PHOTO(
    P_ID        NUMBER,
    P_NAME      VARCHAR2(30 CHAR),
    B_ID        NUMBER
);

CREATE SEQUENCE P_ID NOCACHE;

ALTER TABLE PHOTO ADD CONSTRAINT P_ID_PK PRIMARY KEY(P_ID);
ALTER TABLE PHOTO MODIFY P_NAME CONSTRAINT P_NAME_NN NOT NULL;
ALTER TABLE PHOTO ADD CONSTRAINT P_B_ID_FK FOREIGN KEY(B_ID) REFERENCES BOARD(B_ID) ON DELETE CASCADE;
ALTER TABLE PHOTO MODIFY (P_NAME VARCHAR2(100CHAR));

--------------------------------댓글(COMMENT) 테이블-------------------------------

CREATE TABLE CM(
    CM_ID       NUMBER,
    CM_CONTENT  VARCHAR2(50 CHAR),
    CM_DATE     DATE,
    B_ID        NUMBER,
    M_ID        NUMBER
);

CREATE SEQUENCE CM_ID NOCACHE;

ALTER TABLE CM ADD CONSTRAINT CM_ID_PK PRIMARY KEY(CM_ID);
ALTER TABLE CM MODIFY CM_CONTENT CONSTRAINT CM_CONTENT_NN NOT NULL;
ALTER TABLE CM MODIFY CM_DATE DATE DEFAULT(SYSDATE);
ALTER TABLE CM ADD CONSTRAINT CM_B_ID_FK FOREIGN KEY(B_ID) REFERENCES BOARD(B_ID) ON DELETE CASCADE;
ALTER TABLE CM ADD CONSTRAINT CM_M_ID_FK FOREIGN KEY(M_ID) REFERENCES MEMBER(M_ID) ON DELETE CASCADE;
ALTER TABLE CM MODIFY (CM_CONTENT VARCHAR2(1000 CHAR));

--------------------------------기본 데이터-------------------------------

-----------<관리자 계정>--------
INSERT INTO ACCOUNT VALUES(A_ID.NEXTVAL,'ADMIN','ADMIN','ADMIN',SYSDATE,DEFAULT,'EMAIL','ADDRESS',01011112222,NULL,'M',NULL,NULL);
INSERT INTO AD VALUES(AD_ID.NEXTVAL,A_ID.CURRVAL);

-----------<모임 카테고리>--------
INSERT INTO CG VALUES(CG_ID.NEXTVAL,'취미, 동호회');
INSERT INTO CG VALUES(CG_ID.NEXTVAL,'가족');
INSERT INTO CG VALUES(CG_ID.NEXTVAL,'학교, 동아리');
INSERT INTO CG VALUES(CG_ID.NEXTVAL,'운동');
INSERT INTO CG VALUES(CG_ID.NEXTVAL,'온라인 클래스');
INSERT INTO CG VALUES(CG_ID.NEXTVAL,'회사, 팀');
INSERT INTO CG VALUES(CG_ID.NEXTVAL,'게임');
INSERT INTO CG VALUES(CG_ID.NEXTVAL,'스터디');

-----------<일반 유저 계정>--------
INSERT INTO ACCOUNT VALUES(A_ID.NEXTVAL,'AAAA','AAAA','김동준',11112233,DEFAULT,'EMAIL','ADDRESS',01011111111,NULL,'M',NULL,NULL);
INSERT INTO ACCOUNT VALUES(A_ID.NEXTVAL,'BBBB','BBBB','서인혜',11112233,DEFAULT,'EMAIL','ADDRESS',01022222222,NULL,'W',NULL,NULL);
INSERT INTO ACCOUNT VALUES(A_ID.NEXTVAL,'CCCC','CCCC','이미래영',11112233,DEFAULT,'EMAIL','ADDRESS',01033333333,NULL,'W',NULL,NULL);
INSERT INTO ACCOUNT VALUES(A_ID.NEXTVAL,'DDDD','DDDD','임채성',11112233,DEFAULT,'EMAIL','ADDRESS',01044444444,NULL,'M',NULL,NULL);
INSERT INTO ACCOUNT VALUES(A_ID.NEXTVAL,'EEEE','EEEE','임채연',11112233,DEFAULT,'EMAIL','ADDRESS',01055555555,NULL,'W',NULL,NULL);
INSERT INTO ACCOUNT VALUES(A_ID.NEXTVAL,'FFFF','FFFF','최현우',11112233,DEFAULT,'EMAIL','ADDRESS',01066666666,NULL,'M',NULL,NULL);

